### PR TITLE
Inventory Change handle missing items

### LINKED ISSUE #144: [Bug] Inventory Change Doesn't Detect Decrease to Zero
**Describe the bug**

If you setup an Inventory Alert with type Item Change with a quantity of `-1`, it won't trigger if the remaining items left in your inventory are now zero.

**Expected behavior**
It triggers even if there are no matching items left.

**Code link**

* [The building of the allItems list - only from what is currently in your inventory](https://github.com/adamk33n3r/runelite-watchdog/blob/f98756856929e0505c27c2fa7022526f9b6c67e9/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L212-L214)
* [The looping through your inventory to find which alerts to fire](https://github.com/adamk33n3r/runelite-watchdog/blob/f98756856929e0505c27c2fa7022526f9b6c67e9/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L231-L242)

I think there's two potential solutions:
* Do the same loop with `allItems` and also `this.previousItemsTable` so you can check both.
* Copy the `allItems` map to a new one (as to not mess up [this line](https://github.com/adamk33n3r/runelite-watchdog/blob/f98756856929e0505c27c2fa7022526f9b6c67e9/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L246)), then add any items found from `this.previousItemsTable` to the new map with zero quantity so they don't get missed.

**Additional context**

Sorry I'm pretty sure that was my code that's broken here. 😬

### PR DESCRIPTION
**Pull request by CreativeTechGuy**
Fixes #144, #136

Also fixes `0` having special meaning for Item Count. (If you were using this before, change to > 0)

## Summary by CodeRabbit

- **New Features**
  - Enhanced item tracking to ensure more accurate and real-time updates.
- **Bug Fixes**
  - Improved logic to maintain consistency across item data updates.
- **Documentation**
  - Updated the description for the quantity parameter in InventoryAlertPanel for better clarity.

### CODE REVIEW

**Comment by adamk33n3r** [comment]
Oh hey, this is potentially something I was going to work on so thanks for doing it. Does this handle the case where you have the number set to `0` to? Like if someone wants to know when their inventory runs out of a certain item? It was reported in the Discord https://discord.com/channels/1064234152314015875/1071583176029388880/1231715347296682024

**Comment by adamk33n3r** [comment]
Also, trying out this AI reviewing thing. Sorry :P

**Comment by CreativeTechGuy** [comment]
> Also, trying out this AI reviewing thing. Sorry :P

Haha in this case the AI taught me something since I'm not that great at Java.

> Does this handle the case where you have the number set to 0 to? Like if someone wants to know when their inventory runs out of a certain item?

This is a bit weird, but for Item Count, if you do `< 1` it behaves differently than `== 0`. Because there's currently a special case for `0` which means "any count". I think that's a relic from before the comparators were added. It'd be a breaking change to fix that, would you like me to do that so `0` behaves as actual zero without any special handling?

**Comment by adamk33n3r** [comment]
> This is a bit weird, but for Item Count, if you do `< 1` it behaves differently than `== 0`. Because there's currently a special case for `0` which means "any count". I think that's a relic from before the comparators were added. It'd be a breaking change to fix that, would you like me to do that so `0` behaves as actual zero without any special handling?

Oh right, 0 is the "every time". Maybe we could move that functionality to `-1` and then make `0` work.

The thing is though, I think the code still won't handle it correctly because the user posted that even setting it to `<1` didn't work. And after looking at the code, I think it's because we are only iterating over our inventories current items this tick. So since we no longer have that item in our inventory, it will never be `0`. I think we have to make use of `previousItemsTable` somehow.

If you don't want to handle that case, I can do it on my own time.

**Comment by CreativeTechGuy** [comment]
> Oh right, 0 is the "every time". Maybe we could move that functionality to -1 and then make 0 work.

I don't think we need a special "every time" behavior since you'd just instead do `Item Count > 0`.

> I think we have to make use of previousItemsTable somehow.

That is exactly what this PR solves actually!

**Comment by adamk33n3r** [comment]
> > Oh right, 0 is the "every time". Maybe we could move that functionality to -1 and then make 0 work.
> 
> I don't think we need a special "every time" behavior since you'd just instead do `Item Count > 0`.

Oh you're right! I might have to write a data migration....or just let everyone's alert break that use that which is probably not many :P 

> That is exactly what this PR solves actually!

Oh ok, ya I haven't actually looked at the code yet :P

File: src/main/java/com/adamk33n3r/runelite/watchdog/ui/ComparableNumber.java [hunk 1]
```diff
@@ -21,7 +21,7 @@ public ComparableNumber(
         this.number = PanelUtils.createSpinner(val, min, max, step, onNumChange);
 
         this.setLayout(new DynamicGridLayout(1, 2, 5, 5));
-        this.comparator.setPreferredSize(new Dimension(50, 0));
+        this.comparator.setPreferredSize(new Dimension(100, 0));
```
Comment (adamk33n3r) [inline src/main/java/com/adamk33n3r/runelite/watchdog/ui/ComparableNumber.java:24]: I actually have a better fix for this issue in #143 that I forgot to merge.

Comment (CreativeTechGuy) [reply src/main/java/com/adamk33n3r/runelite/watchdog/ui/ComparableNumber.java:24]: Oh fantastic! I'll remove.

File: src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java [hunk 2]
```diff
@@ -209,9 +209,14 @@ private void onItemContainerChanged(ItemContainerChanged itemContainerChanged) {
             return;
         Item[] items = itemContainerChanged.getItemContainer().getItems();
         long itemCount = Arrays.stream(items).filter(item -> item.getId() > -1).count();
+        Map<Integer, Integer> currentItems = new HashMap<>();
         Map<Integer, Integer> allItems = new HashMap<>();
```
Comment (adamk33n3r) [inline src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java:213]: So the difference is now `currentItems` is what `allItems` used to be, and now `allItems` is `currentItems + previousItems(if missing)`? I think that's making sense to me.

**Review by adamk33n3r — APPROVED** [review]

File: src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java (hunk 2 above)
Comment (CreativeTechGuy) [reply src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java:213]: Yup! Exactly right. I figured the rename was necessary since it wasn't really correct haha

Although a technicality, `allItems` is technically `currentItems + (names of previous items)`. Since it doesn't actually add any quantities from the previous items list, just the existence of them.

Comment (adamk33n3r) [reply src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java:213]: Right, set to `0`. 👍🏻
